const BAD_REQUEST_STATUS_CODE = 400;

const DEFAULT_ERROR = 500;

const REQUEST_NOT_FOUND = 404;

const AUTHORIZATION_ERROR = 401;

const BANNED_ERROR = 403;

const CLASH_ERROR = 409;
module.exports = {
  BAD_REQUEST_STATUS_CODE,
  DEFAULT_ERROR,
  REQUEST_NOT_FOUND,
  CLASH_ERROR,
  AUTHORIZATION_ERROR,
  BANNED_ERROR,
};
